@startuml
'https://plantuml.com/sequence-diagram
header 微信扫码流程图
footer 总览
autonumber
activate 用户 #99FF99
用户 -> 手机: 输入手机密码
activate 手机 #99FF99
手机 --> 用户: 打开手机
deactivate 手机
用户 -> 微信: 打开微信扫一扫
activate 微信 #99FF99
微信-->用户: 返回扫一扫界面
autonumber stop
deactivate 微信
autonumber 5.1
用户 -> 商家: 扫描商家收款码
activate 商家 #99FF99
activate 微信 #99FF99
商家 -> 商家: 生成收款二维码
商家 --> 微信: 返回收款二维码
deactivate 商家
微信 -> 微信: 读取识别商家收款码
autonumber stop
autonumber 6
微信-->用户: 提示输入微信支付密码
autonumber stop
autonumber 7.1
用户 -> 微信: 输入微信支付密码
微信 -> 微信: 微信验证用户输入密码正确
微信 -> 商家: 向商家汇款
activate 商家 #99FF99
商家-->微信: 汇款成功
deactivate 商家
autonumber stop
autonumber 8
微信-->用户: 提示用户支付成功
deactivate 微信
deactivate 用户
@enduml